version: '3.9' # Versio de docker compose
services: # Dins aquest apartat s'han d'especificar els serveis que anem a utilitzar
  sql-srv:
    container_name: sql-srv
    image: adriaprats/mssql-editor.cartas:03.06
    restart: always
    ports:
      - 1433:1433
    volumes:
      - mssql_data:/var/opt/mssql/data
    networks:
      - app

  webservice:
    container_name: webservice
    image: adriaprats/ubuntu_ws:08.06
    restart: on-failure
    command: ["sleep","infinity"] 
      # Per a que apache funcini una vegada tot iniciat haurem de:
        # docker ps -a (agafar id de container)
        # docker exec -it [id] /bin/bash
          # $ service apache2 restart
    build:
      context: . # Executa el Dockerfile
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/SyncDB
    networks:
      - app

networks:
  app:
volumes:
  mssql_data: